name: Monitor DockerHub Repositories

on:
  push:
    branches:
      - master
  schedule:
    # Runs the job at the specified times (UTC)
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  monitor-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Hub CLI
        run: |
          curl -L https://github.com/rofrischmann/docker-hub-cli/releases/latest/download/docker-hub-cli-linux -o dockerhub
          chmod +x dockerhub
          sudo mv dockerhub /usr/local/bin/

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set execute permissions for the script
        run: chmod +x ./monitor_dockerhub.sh

      - name: Show monitor_dockerhub.sh contents
        run: cat ./monitor_dockerhub.sh

      - name: Run monitoring script
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          ./monitor_dockerhub.sh
